In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
sent=[ 'Brave warriors never back down',
'Cloud formations changed with the wind',
'Light filled the room at dawn',
'Sharp minds solve problems quickly',
'Flame flickered in the dark cave',]

In [6]:
#Define the vocabulary size
voc_size=10000

In [7]:
### One hot representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[3067, 3480, 8550, 1828, 8692],
 [1367, 8945, 5015, 9045, 7529, 5929],
 [8290, 5180, 7529, 3166, 3238, 9766],
 [4450, 2792, 9896, 4025, 1207],
 [9914, 2708, 5579, 7529, 3022, 3964]]

In [8]:
##Word Embedding representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 3067 3480 8550 1828 8692]
 [   0    0 1367 8945 5015 9045 7529 5929]
 [   0    0 8290 5180 7529 3166 3238 9766]
 [   0    0    0 4450 2792 9896 4025 1207]
 [   0    0 9914 2708 5579 7529 3022 3964]]


In [11]:
##feature reprresentation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\ann classification\venv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 619ms/step


array([[[ 0.04045165, -0.02904396, -0.04928031, -0.02446183,
         -0.00082964,  0.0210324 ,  0.01552172, -0.0126893 ,
         -0.01879101, -0.02089928],
        [ 0.04045165, -0.02904396, -0.04928031, -0.02446183,
         -0.00082964,  0.0210324 ,  0.01552172, -0.0126893 ,
         -0.01879101, -0.02089928],
        [ 0.04045165, -0.02904396, -0.04928031, -0.02446183,
         -0.00082964,  0.0210324 ,  0.01552172, -0.0126893 ,
         -0.01879101, -0.02089928],
        [ 0.02275202,  0.00528067,  0.00542311,  0.0184609 ,
         -0.00842058,  0.00240369, -0.04765974,  0.00403808,
         -0.03301756, -0.03508883],
        [-0.04609231, -0.04180104,  0.04364477,  0.02963917,
          0.00191154, -0.0492614 ,  0.03996911, -0.00453543,
          0.03741753,  0.02400855],
        [-0.03095937,  0.00809027,  0.0468797 ,  0.04524115,
          0.03321308,  0.0436801 , -0.02447829,  0.03598532,
         -0.00940279,  0.01325843],
        [ 0.0451522 , -0.04148864, -0.03851204, -0.0

In [16]:
embedded_docs[0]

array([   0,    0,    0, 3067, 3480, 8550, 1828, 8692])

In [18]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step


array([[[ 0.04045165, -0.02904396, -0.04928031, -0.02446183,
         -0.00082964,  0.0210324 ,  0.01552172, -0.0126893 ,
         -0.01879101, -0.02089928],
        [ 0.04045165, -0.02904396, -0.04928031, -0.02446183,
         -0.00082964,  0.0210324 ,  0.01552172, -0.0126893 ,
         -0.01879101, -0.02089928],
        [ 0.04045165, -0.02904396, -0.04928031, -0.02446183,
         -0.00082964,  0.0210324 ,  0.01552172, -0.0126893 ,
         -0.01879101, -0.02089928],
        [ 0.02275202,  0.00528067,  0.00542311,  0.0184609 ,
         -0.00842058,  0.00240369, -0.04765974,  0.00403808,
         -0.03301756, -0.03508883],
        [-0.04609231, -0.04180104,  0.04364477,  0.02963917,
          0.00191154, -0.0492614 ,  0.03996911, -0.00453543,
          0.03741753,  0.02400855],
        [-0.03095937,  0.00809027,  0.0468797 ,  0.04524115,
          0.03321308,  0.0436801 , -0.02447829,  0.03598532,
         -0.00940279,  0.01325843],
        [ 0.0451522 , -0.04148864, -0.03851204, -0.0